MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no   # Enable WS2812 RGB underlight
RGB_MATRIX_ENABLE = yes
OLED_ENABLE     = no
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
COMBO_ENABLE = yes
LEADER_ENABLE = yes
COMMAND_ENABLE   = no  # Commands for debug and configuration
UNICODE_ENABLE   = no  # Unicode
SWAP_HANDS_ENABLE= no  # Allow swapping hands of keyboard
SRC += babblePaste.c babl_windows.c babl_mac.c
EXTRAFLAGS        += -flto
